[tool.ruff]
# Enable pycodestyle (E), pyflakes (F), and bugbear (B) rules
select = ["E", "F", "B"]

# Ignore line length violations--Black handles those
line-length = 88
ignore = ["E501"]

target-version = "py37"

src = ["src"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"


[tool.black]
line-length = 88
target-version = ["py38"]

[tool.mypy]
python_version = "3.8"
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "configobj.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "docutils.*"
ignore_missing_imports = true


[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore:::babel[.*]",
    "ignore:::jinja2[.*]",
    "ignore:::yaml[.*]",
    # Sphinx 4.2.0 uses distutils and it's deprecated in 3.10
    "ignore::DeprecationWarning:sphinx",
]


[tool.tox]
legacy_tox_ini = """
[tox]
envlist =
    py38
    py39
    py310
    py311
    py312
    py38-doctest
    py38-lint
    py38-typecheck

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
deps = -rrequirements-dev.txt
commands = pytest {posargs} tests/

[testenv:py38-doctest]
deps = -rrequirements-dev.txt
commands = pytest --doctest-modules src/

[testenv:py38-lint]
basepython = python3.8
changedir = {toxinidir}
commands =
    black --diff setup.py tests docs examples
    ruff src setup.py tests docs examples

[testenv:py38-typecheck]
basepython = python3.8
changedir = {toxinidir}
commands =
    mypy src/everett/
"""
